language: python
python:
- '2.7'

cache: pip
env:
  global:
  - REDISTOGO_URL=redis://localhost:6379
  - secure: NTvqiAz8+qGwOCweP/OCW7jW90rCfE3l4rXqXU0dbQ5MXWjaVyk6FAJeiL3g8pOkbASK4zhAENmoGp8nk2hmZIUi2eoKAvh/CoZl1+6IGwgkIafGnwRASSKtl4GT1Zlc5mPkPnUnPLxjJofB3FlSYrrE5zvkOQc82uZu+t4CM1c=

install: pip install -r requirements.txt
script: make test

deploy:
  provider: heroku
  app: gif2html5
  skip_cleanup: true
  api_key:
    secure: Fjtdzr/e2PRv7cRMRFhU0PgDok2NASskql+YuL8uUJdSeyFGX3JzWpDW7LKjwtFuQ5Se7zFMC2AFex/Pct6a9lY9iqCPQxiiA8Y1rJdIus0PsxOQOD0W3xl8u2mtz75jhpWA75fFM5ilDz/tw7iE/sVWPMB/CfTSvo6TEYB9H78=
